# Booking Cancellation prediction

In [1]:
import pandas as pd

In [3]:
data= pd.read_csv('hotel_booking.csv')
data

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.00,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.00,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.00,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.00,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.00,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,Transient,96.14,0,0,Check-Out,2017-09-06,Claudia Johnson,Claudia.J@yahoo.com,403-092-5582,************8647
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,Transient,225.43,0,2,Check-Out,2017-09-07,Wesley Aguilar,WAguilar@xfinity.com,238-763-0612,************4333
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,Transient,157.71,0,4,Check-Out,2017-09-07,Mary Morales,Mary_Morales@hotmail.com,395-518-4100,************1821
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,Transient,104.40,0,0,Check-Out,2017-09-07,Caroline Conley MD,MD_Caroline@comcast.net,531-528-1017,************7860
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,Transient,151.20,0,2,Check-Out,2017-09-07,Ariana Michael,Ariana_M@xfinity.com,422-804-6403,************4482

In [4]:
data.info

<bound method DataFrame.info of                hotel  is_canceled  lead_time  arrival_date_year  \
0       Resort Hotel            0        342               2015
1       Resort Hotel            0        737               2015
2       Resort Hotel            0          7               2015
3       Resort Hotel            0         13               2015
4       Resort Hotel            0         14               2015
...              ...          ...        ...                ...
119385    City Hotel            0         23               2017
119386    City Hotel            0        102               2017
119387    City Hotel            0         34               2017
119388    City Hotel            0        109               2017
119389    City Hotel            0        205               2017

       arrival_date_month  arrival_date_week_number  \
0                    July                        27
1                    July                        27
2                    July                        27
3                    July                        27
4                    July                        27
...                   ...                       ...
119385             August                        35
119386             August                        35
119387             August                        35
119388             August                        35
119389             August                        35

        arrival_date_day_of_month  stays_in_weekend_nights  \
0                               1                        0
1                               1                        0
2                               1                        0
3                               1                        0
4                               1                        0
...                           ...                      ...
119385                         30                        2
119386                         31                        2
119387                         31                        2
119388                         31                        2
119389                         29                        2

        stays_in_week_nights  adults  ...  customer_type     adr  \
0                          0       2  ...      Transient    0.00
1                          0       2  ...      Transient    0.00
2                          1       1  ...      Transient   75.00
3                          1       1  ...      Transient   75.00
4                          2       2  ...      Transient   98.00
...                      ...     ...  ...            ...     ...
119385                     5       2  ...      Transient   96.14
119386                     5       3  ...      Transient  225.43
119387                     5       2  ...      Transient  157.71
119388                     5       2  ...      Transient  104.40
119389                     7       2  ...      Transient  151.20

       required_car_parking_spaces total_of_special_requests  \
0                                0                         0
1                                0                         0
2                                0                         0
3                                0                         0
4                                0                         1
...                            ...                       ...
119385                           0                         0
119386                           0                         2
119387                           0                         4
119388                           0                         0
119389                           0                         2

       reservation_status reservation_status_date                name  \
0               Check-Out              2015-07-01       Ernest Barnes
1               Check-Out              2015-07-01        Andrea Baker
2               Check-Out              2015-07-02      Rebecca Parker
3               Check-Out              2015-07-02        Laura Murray
4               Check-Out              2015-07-03         Linda Hines
...                   ...                     ...                 ...
119385          Check-Out              2017-09-06     Claudia Johnson
119386          Check-Out              2017-09-07      Wesley Aguilar
119387          Check-Out              2017-09-07        Mary Morales
119388          Check-Out              2017-09-07  Caroline Conley MD
119389          Check-Out              2017-09-07      Ariana Michael

                              email  phone-number       credit_card
0       Ernest.Barnes31@outlook.com  669-792-1661  ************4322
1            Andrea_Baker94@aol.com  858-637-6955  ************9157
2        Rebecca_Parker@comcast.net  652-885-2745  ************3734
3                 Laura_M@gmail.com  364-656-8427  ************5677
4                LHines@verizon.com  713-226-5883  ************5498
...                             ...           ...               ...
119385          Claudia.J@yahoo.com  403-092-5582  ************8647
119386         WAguilar@xfinity.com  238-763-0612  ************4333
119387     Mary_Morales@hotmail.com  395-518-4100  ************1821
119388      MD_Caroline@comcast.net  531-528-1017  ************7860
119389         Ariana_M@xfinity.com  422-804-6403  ************4482

[119390 rows x 36 columns]>

In [5]:
data['distribution_channel']

0            Direct
1            Direct
2            Direct
3         Corporate
4             TA/TO
            ...
119385        TA/TO
119386        TA/TO
119387        TA/TO
119388        TA/TO
119389        TA/TO
Name: distribution_channel, Length: 119390, dtype: object

In [6]:
cat = [i for i in data.columns if data[i].dtypes=='object']
cat

['hotel',
 'arrival_date_month',
 'meal',
 'country',
 'market_segment',
 'distribution_channel',
 'reserved_room_type',
 'assigned_room_type',
 'deposit_type',
 'customer_type',
 'reservation_status',
 'reservation_status_date',
 'name',
 'email',
 'phone-number',
 'credit_card']

In [7]:
len(cat)

16

In [13]:
pd.set_option('display.max_columns',36)

In [15]:
data

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06,Claudia Johnson,Claudia.J@yahoo.com,403-092-5582,************8647
119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07,Wesley Aguilar,WAguilar@xfinity.com,238-763-0612,************4333
119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07,Mary Morales,Mary_Morales@hotmail.com,395-518-4100,************1821
119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07,Caroline Conley MD,MD_Caroline@comcast.net,531-528-1017,************7860
119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07,Ariana Michael,Ariana_M@xfinity.com,422-804-6403,************4482

In [17]:
cat_new =['hotel',
 'arrival_date_month',
 'arrival_date_year',
 'meal',
 'is_repeated_guest',
 'market_segment',
 'distribution_channel',
 'reserved_room_type',
 'assigned_room_type',
 'agent',
 'company',
 'customer_type',
 'reservation_status',
 'email',
 'phone-number',
 'credit_card']

In [19]:
len(cat_new)

16

In [21]:
for i in cat_new:
        if i not in data.columns:
            data[i] = data[i].astype(str)

In [23]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
is_canceled,119390.0,0.370416,0.482918,0.00,0.00,0.000,1.0,1.0
lead_time,119390.0,104.011416,106.863097,0.00,18.00,69.000,160.0,737.0
arrival_date_year,119390.0,2016.156554,0.707476,2015.00,2016.00,2016.000,2017.0,2017.0
arrival_date_week_number,119390.0,27.165173,13.605138,1.00,16.00,28.000,38.0,53.0
arrival_date_day_of_month,119390.0,15.798241,8.780829,1.00,8.00,16.000,23.0,31.0
stays_in_weekend_nights,119390.0,0.927599,0.998613,0.00,0.00,1.000,2.0,19.0
stays_in_week_nights,119390.0,2.500302,1.908286,0.00,1.00,2.000,3.0,50.0
adults,119390.0,1.856403,0.579261,0.00,2.00,2.000,2.0,55.0
children,119386.0,0.103890,0.398561,0.00,0.00,0.000,0.0,10.0
babies,119390.0,0.007949,0.097436,0.00,0.00,0.000,0.0,10.0
is_repeated_guest,119390.0,0.031912,0.175767,0.00,0.00,0.000,0.0,1.0
previous_cancellations,119390.0,0.087118,0.844336,0.00,0.00,0.000,0.0,26.0
previous_bookings_not_canceled,119390.0,0.137097,1.497437,0.00,0.00,0.000,0.0,72.0
booking_changes,119390.0,0.221124,0.652306,0.00,0.00,0.000,0.0,21.0
agent,103050.0,86.693382,110.774548,1.00,9.00,14.000,229.0,535.0
company,6797.0,189.266735,131.655015,6.00,62.00,179.000,270.0,543.0
days_in_waiting_list,119390.0,2.321149,17.594721,0.00,0.00,0.000,0.0,391.0
adr,119390.0,101.831122,50.535790,-6.38,69.29,94.575,126.0,5400.0
required_car_parking_spaces,119390.0,0.062518,0.245291,0.00,0.00,0.000,0.0,8.0
total_of_special_requests,119390.0,0.571363,0.792798,0.00,0.00,0.000,1.0,5.0

In [25]:
data.describe(include='object').T

                          count  unique                  top    freq
hotel                    119390       2           City Hotel   79330
arrival_date_month       119390      12               August   13877
meal                     119390       5                   BB   92310
country                  118902     177                  PRT   48590
market_segment           119390       8            Online TA   56477
distribution_channel     119390       5                TA/TO   97870
reserved_room_type       119390      10                    A   85994
assigned_room_type       119390      12                    A   74053
deposit_type             119390       3           No Deposit  104641
customer_type            119390       4            Transient   89613
reservation_status       119390       3            Check-Out   75166
reservation_status_date  119390     926           2015-10-21    1461
name                     119390   81503      Michael Johnson      48
email                    119390  115889  Michael.C@gmail.com       6
phone-number             119390  119390         669-792-1661       1
credit_card              119390    9000     ************4923      28

In [26]:
data.shape

(119390, 36)

In [27]:
data.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'name', 'email',
       'phone-number', 'credit_card'],
      dtype='object')

# Data leakage

In [32]:
data['reservation_status'].unique()

array(['Check-Out', 'Canceled', 'No-Show'], dtype=object)

In [34]:
for i in ['reservation_status', 'assigned_room_type', 'reservation_status_date']:
    if i in data.columns:
        data.drop(i, inplace=True, axis=1)

In [36]:
data

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,3,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,4,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,0,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,0,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,0,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Linda Hines,LHines@verizon.com,713-226-5883,************5498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,0,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Claudia Johnson,Claudia.J@yahoo.com,403-092-5582,************8647
119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,0,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Wesley Aguilar,WAguilar@xfinity.com,238-763-0612,************4333
119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,0,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Mary Morales,Mary_Morales@hotmail.com,395-518-4100,************1821
119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,0,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Caroline Conley MD,MD_Caroline@comcast.net,531-528-1017,************7860
119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,0,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Ariana Michael,Ariana_M@xfinity.com,422-804-6403,************4482

In [38]:
high_cat = ['country','agent','company','name','email','phone-number','credit_card']

In [40]:
uniques = data[high_cat].nunique()

In [42]:
missing = data[high_cat].isna().sum()
missing

country            488
agent            16340
company         112593
name                 0
email                0
phone-number         0
credit_card          0
dtype: int64

In [44]:
df=pd.DataFrame()

In [46]:
df['column']=high_cat
df['uniques']=list(uniques)
df['missing']=list(missing)
df

         column  uniques  missing
0       country      177      488
1         agent      333    16340
2       company      352   112593
3          name    81503        0
4         email   115889        0
5  phone-number   119390        0
6   credit_card     9000        0

In [48]:
for i in high_cat:
    data.drop(i,axis=1,inplace=True)

In [50]:
data.isna().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          4
babies                            0
meal                              0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
booking_changes                   0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
dtype: int64

In [52]:
data['children'].value_counts()

children
0.0     110796
1.0       4861
2.0       3652
3.0         76
10.0         1
Name: count, dtype: int64

In [54]:
data['children'] = data['children'].fillna(0)

In [56]:
noise = {'adr':data[data['adr']<0],
         'adults':data[data['adults']==0],
         'children':data[data['children']==10],
         'babies':data[data['babies']==10]}

In [58]:
noise_data={i:len(j)for i,j in noise.items()}
noise_data

{'adr': 1, 'adults': 403, 'children': 1, 'babies': 1}

In [60]:
for i in noise.keys():
    data.drop(i,inplace=True,axis=1)

In [62]:
data

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,required_car_parking_spaces,total_of_special_requests
0,Resort Hotel,0,342,2015,July,27,1,0,0,BB,Direct,Direct,0,0,0,C,3,No Deposit,0,Transient,0,0
1,Resort Hotel,0,737,2015,July,27,1,0,0,BB,Direct,Direct,0,0,0,C,4,No Deposit,0,Transient,0,0
2,Resort Hotel,0,7,2015,July,27,1,0,1,BB,Direct,Direct,0,0,0,A,0,No Deposit,0,Transient,0,0
3,Resort Hotel,0,13,2015,July,27,1,0,1,BB,Corporate,Corporate,0,0,0,A,0,No Deposit,0,Transient,0,0
4,Resort Hotel,0,14,2015,July,27,1,0,2,BB,Online TA,TA/TO,0,0,0,A,0,No Deposit,0,Transient,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,BB,Offline TA/TO,TA/TO,0,0,0,A,0,No Deposit,0,Transient,0,0
119386,City Hotel,0,102,2017,August,35,31,2,5,BB,Online TA,TA/TO,0,0,0,E,0,No Deposit,0,Transient,0,2
119387,City Hotel,0,34,2017,August,35,31,2,5,BB,Online TA,TA/TO,0,0,0,D,0,No Deposit,0,Transient,0,4
119388,City Hotel,0,109,2017,August,35,31,2,5,BB,Online TA,TA/TO,0,0,0,A,0,No Deposit,0,Transient,0,0
119389,City Hotel,0,205,2017,August,35,29,2,7,HB,Online TA,TA/TO,0,0,0,A,0,No Deposit,0,Transient,0,2

In [64]:
categorical_feature=[col for col in data.columns if data[col].dtypes=='object']
ohe = [i for i in categorical_feature if i!='arrival_date_month']

In [66]:
data = pd.get_dummies(data,columns=ohe,dtype=int)

In [68]:
pd.set_option('display.max_columns',55)
data

,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,required_car_parking_spaces,total_of_special_requests,hotel_City Hotel,hotel_Resort Hotel,meal_BB,meal_FB,meal_HB,meal_SC,meal_Undefined,market_segment_Aviation,market_segment_Complementary,market_segment_Corporate,market_segment_Direct,market_segment_Groups,market_segment_Offline TA/TO,market_segment_Online TA,market_segment_Undefined,distribution_channel_Corporate,distribution_channel_Direct,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined,reserved_room_type_A,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,reserved_room_type_P,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,0,342,2015,July,27,1,0,0,0,0,0,3,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0
1,0,737,2015,July,27,1,0,0,0,0,0,4,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0
2,0,7,2015,July,27,1,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
3,0,13,2015,July,27,1,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
4,0,14,2015,July,27,1,0,2,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,0,23,2017,August,35,30,2,5,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
119386,0,102,2017,August,35,31,2,5,0,0,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0
119387,0,34,2017,August,35,31,2,5,0,0,0,0,0,0,4,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0
119388,0,109,2017,August,35,31,2,5,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
119389,0,205,2017,August,35,29,2,7,0,0,0,0,0,0,2,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0

In [70]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 52 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   is_canceled                     119390 non-null  int64
 1   lead_time                       119390 non-null  int64
 2   arrival_date_year               119390 non-null  int64
 3   arrival_date_month              119390 non-null  object
 4   arrival_date_week_number        119390 non-null  int64
 5   arrival_date_day_of_month       119390 non-null  int64
 6   stays_in_weekend_nights         119390 non-null  int64
 7   stays_in_week_nights            119390 non-null  int64
 8   is_repeated_guest               119390 non-null  int64
 9   previous_cancellations          119390 non-null  int64
 10  previous_bookings_not_canceled  119390 non-null  int64
 11  booking_changes                 119390 non-null  int64
 12  days_in_waiting_list            119390 non-null  int64
 13  required_car_parking_spaces     119390 non-null  int64
 14  total_of_special_requests       119390 non-null  int64
 15  hotel_City Hotel                119390 non-null  int32
 16  hotel_Resort Hotel              119390 non-null  int32
 17  meal_BB                         119390 non-null  int32
 18  meal_FB                         119390 non-null  int32
 19  meal_HB                         119390 non-null  int32
 20  meal_SC                         119390 non-null  int32
 21  meal_Undefined                  119390 non-null  int32
 22  market_segment_Aviation         119390 non-null  int32
 23  market_segment_Complementary    119390 non-null  int32
 24  market_segment_Corporate        119390 non-null  int32
 25  market_segment_Direct           119390 non-null  int32
 26  market_segment_Groups           119390 non-null  int32
 27  market_segment_Offline TA/TO    119390 non-null  int32
 28  market_segment_Online TA        119390 non-null  int32
 29  market_segment_Undefined        119390 non-null  int32
 30  distribution_channel_Corporate  119390 non-null  int32
 31  distribution_channel_Direct     119390 non-null  int32
 32  distribution_channel_GDS        119390 non-null  int32
 33  distribution_channel_TA/TO      119390 non-null  int32
 34  distribution_channel_Undefined  119390 non-null  int32
 35  reserved_room_type_A            119390 non-null  int32
 36  reserved_room_type_B            119390 non-null  int32
 37  reserved_room_type_C            119390 non-null  int32
 38  reserved_room_type_D            119390 non-null  int32
 39  reserved_room_type_E            119390 non-null  int32
 40  reserved_room_type_F            119390 non-null  int32
 41  reserved_room_type_G            119390 non-null  int32
 42  reserved_room_type_H            119390 non-null  int32
 43  reserved_room_type_L            119390 non-null  int32
 44  reserved_room_type_P            119390 non-null  int32
 45  deposit_type_No Deposit         119390 non-null  int32
 46  deposit_type_Non Refund         119390 non-null  int32
 47  deposit_type_Refundable         119390 non-null  int32
 48  customer_type_Contract          119390 non-null  int32
 49  customer_type_Group             119390 non-null  int32
 50  customer_type_Transient         119390 non-null  int32
 51  customer_type_Transient-Party   119390 non-null  int32
dtypes: int32(37), int64(14), object(1)
memory usage: 30.5+ MB

In [72]:
data['arrival_date_month'].unique()

array(['July', 'August', 'September', 'October', 'November', 'December',
       'January', 'February', 'March', 'April', 'May', 'June'],
      dtype=object)

In [74]:
months=['January', 'February', 'March', 'April', 'May', 'June',
        'July', 'August', 'September', 'October', 'November', 'December']

In [76]:
def mon(x):
    return months.index(x)

# Apply the function to convert month names to indices (0-11) and convert to int
data['arrival_date_month'] = data['arrival_date_month'].apply(mon).astype(int)

In [78]:
data['arrival_date_month'].unique()

array([ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5])

In [80]:
per = data['is_canceled'].value_counts(normalize=True)
per

is_canceled
0    0.629584
1    0.370416
Name: proportion, dtype: float64

In [82]:
X = data.drop('is_canceled',axis=1)
y=data['is_canceled']

In [84]:
X

,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,required_car_parking_spaces,total_of_special_requests,hotel_City Hotel,hotel_Resort Hotel,meal_BB,meal_FB,meal_HB,meal_SC,meal_Undefined,market_segment_Aviation,market_segment_Complementary,market_segment_Corporate,market_segment_Direct,market_segment_Groups,market_segment_Offline TA/TO,market_segment_Online TA,market_segment_Undefined,distribution_channel_Corporate,distribution_channel_Direct,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined,reserved_room_type_A,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,reserved_room_type_P,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,342,2015,6,27,1,0,0,0,0,0,3,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0
1,737,2015,6,27,1,0,0,0,0,0,4,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0
2,7,2015,6,27,1,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
3,13,2015,6,27,1,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
4,14,2015,6,27,1,0,2,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,23,2017,7,35,30,2,5,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
119386,102,2017,7,35,31,2,5,0,0,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0
119387,34,2017,7,35,31,2,5,0,0,0,0,0,0,4,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0
119388,109,2017,7,35,31,2,5,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
119389,205,2017,7,35,29,2,7,0,0,0,0,0,0,2,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0

In [86]:
from sklearn.model_selection import train_test_split

In [87]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [88]:
from sklearn.model_selection import GridSearchCV,StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [89]:
def tuning(cls, parameter, X_train, y_train):
    cv = StratifiedKFold(n_splits=5, shuffle=True)
    cls_grid = GridSearchCV(cls, parameter, cv=cv, scoring='f1', n_jobs=-1)
    cls_grid.fit(X_train, y_train)
    best_hp = cls_grid.best_params_
    return cls_grid.best_estimator_, best_hp

In [90]:
dt_parameter_grid = {
    'criterion':['gini','entropy'],
    'max_depth':[12,13,14]
}

In [93]:
dt = DecisionTreeClassifier(criterion='gini',max_depth=14)
dt.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=14)

In [97]:
best_estimator, best_hp = tuning(dt,dt_parameter_grid,X_train,y_train)

In [98]:
y_pred = dt.predict(X_test)
y_pred

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [100]:
accuracy_score(y_test,y_pred)*100

82.69816009157663

In [101]:
xgb_parameter_grid = {
    'n_estimators':[250,300],
    'learning_rate':[0.01,0.001,0.1],
    'max_depth':[7,8]
}

In [102]:
xgbc = XGBClassifier()

In [103]:
xgbc.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [104]:
y_pred = dt.predict(X_test)
y_pred

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [105]:
accuracy_score(y_test,y_pred)*100

82.69816009157663